on: push
name: on push
jobs:
  gitHubActionForPytest:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for pytest
      uses: filetrust/gw-proxy-serverless@.github
      with:
        args: pytest -h