on: push
name: on push
jobs:
  gitHubActionForPytest:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: GitHub Action for pytest
      uses: filetrust/gw-proxy-serverless@adding-github-actions
      with:
        args: pytest tests